spring:
  application:
    name: authhub
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/authhub
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/authhub
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    locations: classpath:db/migration # location for flyway
  sql:
    init:
      mode: always # Flyway did not work, using schema.sql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master # use mailhub realm
#          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

server:
  port: 8085


management:
  endpoints:
    web:
      exposure:
        include: health, info

crypto:
  master-key: ${MASTER_KEY_ENCRYPTION}

authhub:
  oauth:
    providers:
      gmail:
        id: gmail
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        authorize-uri: https://accounts.google.com/o/oauth2/v2/auth
        token-uri: https://oauth2.googleapis.com/token
        redirect-uri: http://<AUTHUB_URL>/oauth/gmail/callback
        scopes: ["https://www.googleapis.com/auth/gmail.readonly"]
        params: "&prompt=consent&access_type=offline"
